"""
verify_readouts.jl — parity check for Codebook + SSMReadout.

Loads HDF5 fixtures generated by `julia_parity/generate_parity_readouts.py`
and asserts that Lux's Codebook / SSMReadout, initialized with PyTorch's
saved `codes`, produce the same forward output (within tolerance) on the
same canned input.

Run:
  julia --project=julia_parity julia_parity/verify_readouts.jl
"""

using HDF5, PhasorNetworks, Lux, Random, Statistics

include(joinpath(@__DIR__, "load_pytorch.jl"))
using .PhasorTorchLoad

const FIXTURES = joinpath(@__DIR__, "fixtures")
const TOL = 1e-5

# Enumerate fixtures whose names look like readouts (codebook_* or ssm_readout_*).
function enumerate_readout_cases(dir::AbstractString)
    cases = NamedTuple[]
    for path in sort(readdir(dir; join=true))
        endswith(path, "_weights.h5") || continue
        base = replace(basename(path), "_weights.h5" => "")
        (startswith(base, "codebook_") || startswith(base, "ssm_readout_")) || continue
        io_path = joinpath(dir, "$(base)_io.h5")
        isfile(io_path) || continue
        push!(cases, (; name = base, weights_path = path, io_path = io_path))
    end
    return cases
end

# Build a Lux Codebook with codes injected directly (skip init).
function _wrap_phase_array(arr)
    return Phase.(arr)
end

function verify_case(case; tol=TOL)
    meta = load_meta(case.weights_path)
    kind = meta["kind"]
    inputs, outputs = load_io_pair(case.io_path)
    x_raw = inputs["x"]
    y_expected = outputs["y"]

    if kind == "codebook"
        d = parse(Int, meta["d"])
        n = parse(Int, meta["K"])
        layer = Codebook(d => n; init_mode = Symbol(meta["init_mode"]))
        raw_state = load_params(case.weights_path, "codebook")
        codes_raw = raw_state.codes
        # PyTorch saved (d, n); Julia row-major HDF5 read gives (n, d) -> transpose.
        codes = permutedims(codes_raw, (2, 1))
        @assert size(codes) == (d, n) "Codebook codes shape $(size(codes)) != ($d, $n)"
        st = (codes = _wrap_phase_array(codes),)
        ps = NamedTuple()

        # Input: PyTorch (d, B) -> Julia HDF5 read (B, d) -> transpose.
        x = permutedims(x_raw, (2, 1))                      # (d, B)
        x_phase = _wrap_phase_array(x)
        y_got, _ = layer(x_phase, ps, st)

        # Expected: PyTorch (n, B) -> Julia HDF5 read (B, n) -> transpose.
        y_expected = permutedims(y_expected, (2, 1))         # (n, B)
    else
        d = parse(Int, meta["d"])
        n = parse(Int, meta["K"])
        L = parse(Int, meta["L"])
        frac = parse(Float32, meta["readout_frac"])
        layer = SSMReadout(d => n; readout_frac = frac)
        raw_state = load_params(case.weights_path, "readout")
        codes = permutedims(raw_state.codes, (2, 1))         # (d, n)
        @assert size(codes) == (d, n)
        st = (codes = _wrap_phase_array(codes),)
        ps = NamedTuple()

        # Input: PyTorch (d, L, B) -> Julia (B, L, d) -> permute to (d, L, B).
        x = permutedims(x_raw, (3, 2, 1))
        x_phase = _wrap_phase_array(x)
        y_got, _ = layer(x_phase, ps, st)

        # Expected: PyTorch (n, B) -> Julia (B, n) -> transpose.
        y_expected = permutedims(y_expected, (2, 1))
    end

    y_got_f32 = Float32.(y_got)
    err = maximum(abs.(y_got_f32 .- y_expected))
    status = err <= tol ? "PASS" : "FAIL"
    @info "case=$(case.name) kind=$kind max|err|=$(round(err, sigdigits=5)) ($status)"
    return err
end

function main()
    cases = enumerate_readout_cases(FIXTURES)
    isempty(cases) && error("no readout fixtures in $FIXTURES -- run generate_parity_readouts.py first")
    failures = String[]
    for case in cases
        err = verify_case(case)
        if err > TOL
            push!(failures, "$(case.name): max|err|=$err > tol=$TOL")
        end
    end
    if !isempty(failures)
        for f in failures
            @error f
        end
        error("Readout parity FAILED for $(length(failures)) case(s).")
    end
    @info "Readout parity: ALL CASES PASS (tol=$TOL)"
end

isinteractive() || main()
