"""
verify_phasor_residual.jl — PhasorTransformerBlock parity check.

Loads HDF5 fixtures generated by
`julia_parity/generate_parity_phasor_residual.py` and asserts that Lux's
PhasorTransformerBlock (PhasorResidual + PhaseRecenter + FFN around PhasorLSA /
PhasorLCA), initialized from PyTorch's saved weights, produces the same forward
output on the same canned input.

Run:
  julia --project=julia_parity julia_parity/verify_phasor_residual.jl
"""

using HDF5, PhasorNetworks, Lux, Random, Statistics

include(joinpath(@__DIR__, "load_pytorch.jl"))
using .PhasorTorchLoad

const FIXTURES = joinpath(@__DIR__, "fixtures")
const TOL = 1e-5
# Long-sequence cases run the FFT branch of causal_conv inside every projection
# and FFN dense; their compounded float32 error is ~1e-4.
const TOL_LONG = 5e-4
_tol_for(name) = occursin("long", name) ? TOL_LONG : TOL

function enumerate_residual_cases(dir::AbstractString)
    cases = NamedTuple[]
    for path in sort(readdir(dir; join=true))
        endswith(path, "_weights.h5") || continue
        base = replace(basename(path), "_weights.h5" => "")
        startswith(base, "res_") || continue
        io_path = joinpath(dir, "$(base)_io.h5")
        isfile(io_path) || continue
        push!(cases, (; name = base, weights_path = path, io_path = io_path))
    end
    return cases
end

_use_ffn(meta) = get(meta, "use_ffn", "True") == "True"

function _build_attn(meta)
    D = parse(Int, meta["d_model"])
    n_heads = parse(Int, meta["n_heads"])
    init_scale = parse(Float32, meta["init_scale"])
    t_period = parse(Float32, meta["t_period"])
    spk = SpikingArgs(t_period = t_period)
    if meta["kind"] == "lsa"
        return PhasorLSA(D => D, n_heads, normalize_to_unit_circle;
                         init_scale = init_scale, init_mode = :hippo, spk_args = spk)
    else
        n_anchors = parse(Int, meta["n_anchors"])
        return PhasorLCA(D => D, n_heads, n_anchors, normalize_to_unit_circle;
                         init_scale = init_scale, init_mode = :hippo, spk_args = spk)
    end
end

function build_block(meta)
    D = parse(Int, meta["d_model"])
    gate = Symbol(meta["gate"])
    alpha0 = parse(Float32, meta["alpha0"])
    bis = parse(Float32, meta["branch_init_scale"])
    recenter = meta["recenter"] == "True"
    d_ff = parse(Int, meta["d_ff"])
    d_ff_eff = d_ff > 0 ? d_ff : D
    attn = _build_attn(meta)

    if !_use_ffn(meta)
        # Attn-only block: the Julia equivalent of a use_ffn=False PyTorch
        # PhasorTransformerBlock is a bare PhasorResidual(attn) (optionally
        # pre-normed). There is no ffn_res.
        attn_branch = recenter ? Chain(PhaseRecenter(), attn) : attn
        return PhasorResidual(attn_branch; gate = gate, alpha0 = alpha0)
    end
    return PhasorTransformerBlock(D, attn; d_ff = d_ff_eff, gate = gate,
                                  alpha0 = alpha0, branch_init_scale = bis,
                                  recenter = recenter)
end

# --- per-component param injection (PyTorch -> Lux) -----------------------

# bias-free PhasorDense (Q/K/V projections).
_proj(p) = (weight = permutedims(p.weight, (2, 1)),
            log_neg_lambda = vec(p.log_neg_lambda))

# bias-carrying PhasorDense (FFN denses).
_dense(p) = (weight = permutedims(p.weight, (2, 1)),
             log_neg_lambda = vec(p.log_neg_lambda),
             bias_real = vec(p.bias_real),
             bias_imag = vec(p.bias_imag))

function _attn_inner(kind, sub)
    if kind == "lsa"
        return (q_proj = _proj(sub.q_proj),
                k_proj = _proj(sub.k_proj),
                v_proj = _proj(sub.v_proj),
                scale  = vec(sub.scale))
    else
        return (k_proj = _proj(sub.k_proj),
                v_proj = _proj(sub.v_proj),
                anchors = Phase.(permutedims(sub.anchors, (2, 1))),
                scale  = vec(sub.scale))
    end
end

# Wrap an inner param tree in the Chain(PhaseRecenter, inner) layout Lux uses
# when recenter=true. PhaseRecenter is parameter-free -> empty NamedTuple.
_maybe_recenter(inner, recenter) =
    recenter ? (layer_1 = NamedTuple(), layer_2 = inner) : inner

# Build a PhasorResidual param tree: (layer = ..., [alpha = ...]).
function _residual(layer_ps, raw_res, rezero)
    return rezero ? (layer = layer_ps, alpha = vec(raw_res.alpha)) :
                    (layer = layer_ps,)
end

function inject_block(raw::NamedTuple, meta)
    kind = meta["kind"]
    recenter = meta["recenter"] == "True"
    rezero = meta["gate"] == "rezero"

    attn_inner = _attn_inner(kind, raw.attn_res.sublayer)
    attn_layer = _maybe_recenter(attn_inner, recenter)

    if !_use_ffn(meta)
        # The model IS a single PhasorResidual, so its param tree is the
        # residual's own (layer = ..., [alpha = ...]) -- not wrapped in attn_res.
        return _residual(attn_layer, raw.attn_res, rezero)
    end

    ffn_inner  = (layer_1 = _dense(raw.ffn_res.sublayer.fc1),
                  layer_2 = _dense(raw.ffn_res.sublayer.fc2))
    ffn_layer  = _maybe_recenter(ffn_inner, recenter)

    return (attn_res = _residual(attn_layer, raw.attn_res, rezero),
            ffn_res  = _residual(ffn_layer,  raw.ffn_res,  rezero))
end

function verify_case(case; tol=_tol_for(case.name))
    meta = load_meta(case.weights_path)
    mode = meta["mode"]
    block = build_block(meta)
    raw = load_params(case.weights_path, "block")
    ps = inject_block(raw, meta)
    st = Lux.initialstates(Random.default_rng(), block)

    inputs, outputs = load_io_pair(case.io_path)
    x_raw = inputs["x"]
    y_expected_raw = outputs["y"]

    if mode == "2d"
        x = permutedims(x_raw, (2, 1))
        y_expected = permutedims(y_expected_raw, (2, 1))
    else
        x = permutedims(x_raw, (3, 2, 1))
        y_expected = permutedims(y_expected_raw, (3, 2, 1))
    end
    x_phase = Phase.(x)

    y_got, _ = block(x_phase, ps, st)
    y_got_f32 = Float32.(y_got)
    err = maximum(abs.(y_got_f32 .- y_expected))

    status = err <= tol ? "PASS" : "FAIL"
    @info "case=$(case.name) mode=$mode max|err|=$(round(err, sigdigits=5)) ($status)"
    return err
end

function main()
    cases = enumerate_residual_cases(FIXTURES)
    isempty(cases) && error("no residual fixtures in $FIXTURES -- run generate_parity_phasor_residual.py first")
    failures = String[]
    for case in cases
        tol = _tol_for(case.name)
        err = verify_case(case; tol=tol)
        if err > tol
            push!(failures, "$(case.name): max|err|=$err > tol=$tol")
        end
    end
    if !isempty(failures)
        for f in failures
            @error f
        end
        error("PhasorTransformerBlock parity FAILED for $(length(failures)) case(s).")
    end
    @info "PhasorTransformerBlock parity: ALL CASES PASS"
end

isinteractive() || main()
