"""
verify_phasor_lsa.jl — PhasorLSA parity check.

Loads HDF5 fixtures generated by `julia_parity/generate_parity_phasor_lsa.py`
and asserts that Lux's PhasorLSA, initialized from PyTorch's saved weights,
produces the same forward output (within tolerance) on the same canned input.

Run:
  julia --project=julia_parity julia_parity/verify_phasor_lsa.jl
"""

using HDF5, PhasorNetworks, Lux, Random, Statistics

include(joinpath(@__DIR__, "load_pytorch.jl"))
using .PhasorTorchLoad

const FIXTURES = joinpath(@__DIR__, "fixtures")
const TOL = 1e-5
# Long-sequence cases use the FFT branch of causal_conv inside each of the
# three q/k/v projections; their compounded float32 error is ~1e-4. We
# relax the tolerance only for the explicit long-sequence fixture.
const TOL_LONG = 5e-4
_tol_for(name) = occursin("long", name) ? TOL_LONG : TOL

function enumerate_lsa_cases(dir::AbstractString)
    cases = NamedTuple[]
    for path in sort(readdir(dir; join=true))
        endswith(path, "_weights.h5") || continue
        base = replace(basename(path), "_weights.h5" => "")
        startswith(base, "lsa_") || continue
        io_path = joinpath(dir, "$(base)_io.h5")
        isfile(io_path) || continue
        push!(cases, (; name = base, weights_path = path, io_path = io_path))
    end
    return cases
end

# Build a Lux PhasorLSA matching the PyTorch case metadata.
function build_layer(meta)
    in_d = parse(Int, meta["in_dims"])
    d_model = parse(Int, meta["d_model"])
    n_heads = parse(Int, meta["n_heads"])
    init_mode = Symbol(meta["init_mode"])
    init_scale = parse(Float32, meta["init_scale"])
    t_period = parse(Float32, meta["t_period"])
    spk = SpikingArgs(t_period = t_period)
    return PhasorLSA(in_d => d_model, n_heads, normalize_to_unit_circle;
                     init_scale = init_scale, init_mode = init_mode, spk_args = spk)
end

# Inject PyTorch params: transpose 2D weights, vec the 1D arrays.
function inject_params(raw::NamedTuple)
    function _proj(name::Symbol)
        sub = getproperty(raw, name)
        return (weight = permutedims(sub.weight, (2, 1)),
                log_neg_lambda = vec(sub.log_neg_lambda))
    end
    return (q_proj = _proj(:q_proj),
            k_proj = _proj(:k_proj),
            v_proj = _proj(:v_proj),
            scale  = vec(raw.scale))   # (1,) Float32
end

function verify_case(case; tol=_tol_for(case.name))
    meta = load_meta(case.weights_path)
    mode = meta["mode"]
    layer = build_layer(meta)
    raw = load_params(case.weights_path, "attn")
    ps = inject_params(raw)
    st = Lux.initialstates(Random.default_rng(), layer)

    inputs, outputs = load_io_pair(case.io_path)
    x_raw = inputs["x"]
    y_expected_raw = outputs["y"]

    if mode == "2d"
        # PyTorch (in_dims, B) -> Julia (B, in_dims) -> transpose
        x = permutedims(x_raw, (2, 1))
        y_expected = permutedims(y_expected_raw, (2, 1))
    else
        # PyTorch (in_dims, L, B) -> Julia (B, L, in_dims) -> permute
        x = permutedims(x_raw, (3, 2, 1))
        y_expected = permutedims(y_expected_raw, (3, 2, 1))
    end
    x_phase = Phase.(x)

    y_got, _ = layer(x_phase, ps, st)
    y_got_f32 = Float32.(y_got)
    err = maximum(abs.(y_got_f32 .- y_expected))

    status = err <= tol ? "PASS" : "FAIL"
    @info "case=$(case.name) mode=$mode max|err|=$(round(err, sigdigits=5)) ($status)"
    return err
end

function main()
    cases = enumerate_lsa_cases(FIXTURES)
    isempty(cases) && error("no LSA fixtures in $FIXTURES -- run generate_parity_phasor_lsa.py first")
    failures = String[]
    for case in cases
        tol = _tol_for(case.name)
        err = verify_case(case; tol=tol)
        if err > tol
            push!(failures, "$(case.name): max|err|=$err > tol=$tol")
        end
    end
    if !isempty(failures)
        for f in failures
            @error f
        end
        error("PhasorLSA parity FAILED for $(length(failures)) case(s).")
    end
    @info "PhasorLSA parity: ALL CASES PASS (tol=$TOL)"
end

isinteractive() || main()
