"""
verify_phasor_dense.jl — PhasorDense parity check.

Loads HDF5 fixtures generated by `julia_parity/generate_parity_phasor_dense.py`
and asserts that Lux's PhasorDense, initialized from PyTorch's saved weights,
produces the same forward output (within tolerance) on the same canned input.

Run (after `julia --project=julia_parity -e 'using Pkg; Pkg.instantiate()'`):
  julia --project=julia_parity julia_parity/verify_phasor_dense.jl
"""

using HDF5, PhasorNetworks, Lux, Random, Statistics

include(joinpath(@__DIR__, "load_pytorch.jl"))
using .PhasorTorchLoad

const FIXTURES = joinpath(@__DIR__, "fixtures")
const TOL = 1e-5

# -------------------------------------------------------------------------
# Fixture enumeration (replaces the JSON manifest).
# -------------------------------------------------------------------------

"""
    enumerate_cases(dir) -> Vector{NamedTuple}

Globs `*_weights.h5` in `dir` and pairs each with its `_io.h5` sibling.
Returns NamedTuples with fields :name, :weights_path, :io_path.
"""
function enumerate_cases(dir::AbstractString)
    cases = NamedTuple[]
    for path in sort(readdir(dir; join=true))
        endswith(path, "_weights.h5") || continue
        name = replace(basename(path), "_weights.h5" => "")
        startswith(name, "dense_") || continue           # ignore other layers' fixtures
        io_path = joinpath(dir, "$(name)_io.h5")
        isfile(io_path) || (@warn "no IO pair for $name"; continue)
        push!(cases, (; name = name, weights_path = path, io_path = io_path))
    end
    return cases
end

# -------------------------------------------------------------------------
# Build a Lux PhasorDense matching the PyTorch case metadata.
# -------------------------------------------------------------------------

function build_lux_layer(meta::Dict)
    in_d = parse(Int, meta["in_dims"])
    out_d = parse(Int, meta["out_dims"])
    use_bias = meta["use_bias"] == "True"
    init_mode = Symbol(meta["init_mode"])
    t_period = parse(Float32, meta["t_period"])
    spk = SpikingArgs(t_period=t_period)

    return PhasorDense(in_d => out_d, normalize_to_unit_circle;
                       use_bias=use_bias,
                       init_mode=init_mode,
                       spk_args=spk)
end

# -------------------------------------------------------------------------
# Override Lux-initialized parameters with the values from HDF5.
# -------------------------------------------------------------------------

function injected_params(layer::PhasorDense, raw::NamedTuple)
    # PyTorch saves weight as (out_dims, in_dims) in row-major. HDF5
    # round-trips through column-major Julia as (in_dims, out_dims), so
    # restore the (out, in) layout Lux expects.
    weight = permutedims(raw.weight, (2, 1))
    log_neg_lambda = vec(raw.log_neg_lambda)
    if layer.use_bias
        bias_real = vec(raw.bias_real)
        bias_imag = vec(raw.bias_imag)
        return (weight = weight,
                log_neg_lambda = log_neg_lambda,
                bias_real = bias_real,
                bias_imag = bias_imag)
    else
        return (weight = weight, log_neg_lambda = log_neg_lambda)
    end
end

# -------------------------------------------------------------------------
# Run forward, compare to saved output.
# -------------------------------------------------------------------------

function _wrap_phase(x::Array{Float32, 2})
    return Phase.(x)
end
function _wrap_phase(x::Array{Float32, 3})
    return Phase.(x)
end

function verify_case(case; tol=TOL)
    name = case.name
    weights_path = case.weights_path
    io_path = case.io_path

    meta = load_meta(weights_path)
    mode = meta["mode"]
    layer = build_lux_layer(meta)

    raw = load_params(weights_path, "dense")
    ps  = injected_params(layer, raw)
    st  = Lux.initialstates(Random.default_rng(), layer)

    inputs, outputs = load_io_pair(io_path)
    x_raw = inputs["x"]
    y_expected = outputs["y"]

    # Permute axes if needed. The PyTorch tensors are saved in
    # PyTorch-native layout (Channel-First, time before batch). HDF5
    # preserves row-major order; h5py writes (C_in, B) or (C_in, L, B).
    # When read into Julia (column-major), the apparent shape is reversed:
    # what was (C_in, B) in PyTorch comes back as (B, C_in) in Julia.
    # Permute to restore Julia's (C_in, B) / (C_in, L, B) convention.
    if mode == "2d"
        @assert ndims(x_raw) == 2
        x = permutedims(x_raw, (2, 1))                        # (C_in, B)
        y_expected = permutedims(y_expected, (2, 1))          # (out, B)
    elseif mode == "3d"
        @assert ndims(x_raw) == 3
        x = permutedims(x_raw, (3, 2, 1))                     # (C_in, L, B)
        y_expected = permutedims(y_expected, (3, 2, 1))       # (out, L, B)
    else
        error("unknown mode '$mode'")
    end

    x_phase = _wrap_phase(x)
    y_got, _ = layer(x_phase, ps, st)

    # y_got is an array of Phase; coerce to Float32 for comparison.
    y_got_f32 = Float32.(y_got)
    err = maximum(abs.(y_got_f32 .- y_expected))

    status = err <= tol ? "PASS" : "FAIL"
    @info "case=$name mode=$mode max|err|=$(round(err, sigdigits=5)) ($status)"

    return err
end

function main()
    isdir(FIXTURES) ||
        error("fixtures dir not found at $FIXTURES -- run generate_parity_phasor_dense.py first")

    cases = enumerate_cases(FIXTURES)
    isempty(cases) && error("no parity cases found in $FIXTURES")

    failures = String[]
    for case in cases
        err = verify_case(case)
        if err > TOL
            push!(failures, "$(case.name): max|err|=$err > tol=$TOL")
        end
    end

    if !isempty(failures)
        for f in failures
            @error f
        end
        error("PhasorDense parity FAILED for $(length(failures)) case(s).")
    end
    @info "PhasorDense parity: ALL CASES PASS (tol=$TOL)"
end

isinteractive() || main()
