"""
verify_end_to_end.jl — Stage 7 round-trip check.

Loads the PyTorch-trained checkpoint + test fixtures generated by
`julia_parity/train_and_save_for_julia.py`, rebuilds the equivalent Lux
Chain, runs forward on the same test inputs, and compares:
  1. per-sample similarity scores (should match PyTorch's saved sims).
  2. argmax-accuracy (should equal PyTorch's saved test accuracy).

Run:
  julia --project=julia_parity julia_parity/verify_end_to_end.jl
"""

using HDF5, PhasorNetworks, Lux, Random, Statistics

include(joinpath(@__DIR__, "load_pytorch.jl"))
using .PhasorTorchLoad

const FIXTURES = joinpath(@__DIR__, "fixtures")
const WEIGHTS  = joinpath(FIXTURES, "e2e_chain_weights.h5")
const IO       = joinpath(FIXTURES, "e2e_chain_io.h5")
# Similarity-score tolerance is loose because the chain goes through three
# PhasorDense forwards plus a head mix plus an SSMReadout average — at
# float32 with FFT in the conv path, ~1e-3 is realistic. Accuracy is
# expected to match exactly (it's an argmax).
const SCORES_TOL = 5e-3

function main()
    isfile(WEIGHTS) || error("missing $WEIGHTS -- run train_and_save_for_julia.py first")
    isfile(IO)      || error("missing $IO")

    # The IO fixture carries the canonical metadata (architecture + PyTorch
    # eval results). The weights file's metadata is the auto-generated
    # `cfg.*` flatten of the RunConfig, which is fine but less direct.
    meta = load_meta(IO)
    n_classes  = parse(Int, meta["n_classes"])
    d_hidden   = parse(Int, meta["d_hidden"])
    n_heads    = parse(Int, meta["n_heads"])
    in_dims    = parse(Int, meta["in_dims"])
    init_mode  = Symbol(meta["init_mode"])
    init_scale = parse(Float32, meta["init_scale"])
    t_period   = parse(Float32, meta["t_period"])
    rfrac      = parse(Float32, meta["readout_frac"])
    pt_acc     = parse(Float32, meta["pt_test_acc"])
    spk = SpikingArgs(t_period = t_period)

    # ----- Rebuild the chain (must mirror build_model in phasor_torch/train.py).
    # Input embedding now carries a complex bias (build_model use_bias=True) to
    # keep |z| off the origin; uniform lambda init.
    layer_input = PhasorDense(in_dims => d_hidden, normalize_to_unit_circle;
                              use_bias = true, init_mode = init_mode, spk_args = spk)
    layer_body  = PhasorLSA(d_hidden => d_hidden, n_heads, normalize_to_unit_circle;
                            init_scale = init_scale, init_mode = init_mode, spk_args = spk)
    layer_dense = PhasorDense(d_hidden => d_hidden, identity;
                              use_bias = false, init_mode = init_mode, spk_args = spk)
    layer_ro    = SSMReadout(d_hidden => n_classes; readout_frac = rfrac)

    rng = Random.default_rng()
    ps_input = Lux.initialparameters(rng, layer_input)
    ps_body  = Lux.initialparameters(rng, layer_body)
    ps_dense = Lux.initialparameters(rng, layer_dense)
    st_ro    = Lux.initialstates(rng, layer_ro)

    # ----- Load weights and override the Lux init.
    function _dense_ps(grp_name::AbstractString; with_bias::Bool=false)
        raw = load_params(WEIGHTS, grp_name)
        if with_bias
            return (weight = permutedims(raw.weight, (2, 1)),
                    log_neg_lambda = vec(raw.log_neg_lambda),
                    bias_real = vec(raw.bias_real),
                    bias_imag = vec(raw.bias_imag))
        end
        return (weight = permutedims(raw.weight, (2, 1)),
                log_neg_lambda = vec(raw.log_neg_lambda))
    end

    ps_input = _dense_ps("input"; with_bias=true)

    raw_body = load_params(WEIGHTS, "body")
    function _proj(sub::Symbol)
        s = getproperty(raw_body, sub)
        return (weight = permutedims(s.weight, (2, 1)),
                log_neg_lambda = vec(s.log_neg_lambda))
    end
    ps_body = (q_proj = _proj(:q_proj),
               k_proj = _proj(:k_proj),
               v_proj = _proj(:v_proj),
               scale  = vec(raw_body.scale))

    ps_dense = _dense_ps("dense")

    raw_ro = load_params(WEIGHTS, "readout")
    st_ro = (codes = Phase.(permutedims(raw_ro.codes, (2, 1))),)

    # ----- Test inputs.
    inputs, outputs = load_io_pair(IO)
    x_raw    = inputs["x"]        # PyTorch (C, L, N) -> Julia (N, L, C)
    labels   = inputs["labels"]   # PyTorch (N,) float -> Julia (N,)
    sims_exp = outputs["sims"]    # PyTorch (n_classes, N) -> Julia (N, n_classes)

    x = permutedims(x_raw, (3, 2, 1))            # (C, L, N) in Julia
    sims_expected = permutedims(sims_exp, (2, 1)) # (n_classes, N) in Julia
    labels_int = Int.(round.(labels))             # already 0..n-1

    x_phase = Phase.(x)

    # ----- Forward.
    y1, _ = layer_input(x_phase, ps_input, Lux.initialstates(rng, layer_input))
    y2, _ = layer_body(y1,        ps_body,  Lux.initialstates(rng, layer_body))
    y3, _ = layer_dense(y2,       ps_dense, Lux.initialstates(rng, layer_dense))
    sims_got, _ = layer_ro(y3,    NamedTuple(), st_ro)        # (n_classes, N)

    # ----- Compare.
    sims_got_f32 = Float32.(sims_got)
    score_err = maximum(abs.(sims_got_f32 .- sims_expected))
    @info "max|err| on similarity scores = $(round(score_err, sigdigits=5))" *
          " (tol=$SCORES_TOL)"

    # Julia accuracy.
    julia_preds = vec([argmax(view(sims_got_f32, :, i)) - 1 for i in axes(sims_got_f32, 2)])
    julia_acc   = mean(julia_preds .== labels_int)
    @info "Julia test acc = $(round(julia_acc, sigdigits=4))" *
          "  |  PyTorch test acc = $(round(pt_acc, sigdigits=4))"

    if score_err > SCORES_TOL
        error("score parity failed: max|err|=$score_err > $SCORES_TOL")
    end
    acc_diff = abs(julia_acc - pt_acc)
    if acc_diff > 0.01     # within 1 percentage point
        error("accuracy mismatch: PyTorch $pt_acc vs Julia $julia_acc (diff=$acc_diff)")
    end
    @info "Stage 7 PASS: PyTorch -> Julia chain forward agrees within tolerance."
end

isinteractive() || main()
