"""
verify_resonant_stft.jl — ResonantSTFT parity check.

Loads HDF5 fixtures generated by `generate_parity_resonant_stft.py` and asserts
that Lux's ResonantSTFT, initialized from PyTorch's saved weights, produces the
same forward output (within tolerance) on the same canned complex input.

Exercises the 3D-Complex dispatch (the audio path) across SLERP / normalize /
identity activations, bias on/off, and Toeplitz (short) vs FFT (long) sequences.

Run:
  julia --project=julia_parity julia_parity/verify_resonant_stft.jl
"""

using HDF5, PhasorNetworks, Lux, Random, Statistics

include(joinpath(@__DIR__, "load_pytorch.jl"))
using .PhasorTorchLoad

const FIXTURES = joinpath(@__DIR__, "fixtures")
const TOL = 1e-5
# Long-sequence cases use the FFT branch of causal_conv; compounded float32
# error is ~1e-4. Relax tolerance only for the explicit long-sequence fixtures.
const TOL_LONG = 5e-4
_tol_for(name) = occursin("long", name) ? TOL_LONG : TOL

function enumerate_cases(dir::AbstractString)
    cases = NamedTuple[]
    for path in sort(readdir(dir; join=true))
        endswith(path, "_weights.h5") || continue
        base = replace(basename(path), "_weights.h5" => "")
        startswith(base, "rstft_") || continue
        io_path = joinpath(dir, "$(base)_io.h5")
        isfile(io_path) || continue
        push!(cases, (; name = base, weights_path = path, io_path = io_path))
    end
    return cases
end

function _activation(name::AbstractString)
    name == "slerp"     && return nothing
    name == "normalize" && return normalize_to_unit_circle
    name == "identity"  && return identity
    error("unknown activation $name")
end

function build_layer(meta)
    in_d = parse(Int, meta["in_dims"])
    n_freqs = parse(Int, meta["n_freqs"])
    use_bias = parse(Bool, meta["use_bias"])
    t_period = parse(Float32, meta["t_period"])
    spk = SpikingArgs(t_period = t_period)
    act = _activation(meta["activation"])
    return ResonantSTFT(in_d => n_freqs, act; use_bias = use_bias, spk_args = spk)
end

# Inject PyTorch params: transpose the 2D weight, vec the 1D arrays, and include
# bias / SLERP-threshold params only when the case has them.
function inject_params(raw::NamedTuple, act_name::AbstractString, use_bias::Bool)
    ps = (weight = permutedims(raw.weight, (2, 1)),
          log_neg_lambda = vec(raw.log_neg_lambda),
          omega = vec(raw.omega))
    if use_bias
        ps = merge(ps, (bias_real = vec(raw.bias_real),
                        bias_imag = vec(raw.bias_imag)))
    end
    if act_name == "slerp"
        ps = merge(ps, (log_r_lo = vec(raw.log_r_lo),
                        log_r_gap = vec(raw.log_r_gap)))
    end
    return ps
end

function verify_case(case; tol = _tol_for(case.name))
    meta = load_meta(case.weights_path)
    use_bias = parse(Bool, meta["use_bias"])
    act_name = meta["activation"]

    layer = build_layer(meta)
    raw = load_params(case.weights_path, "stft")
    ps = inject_params(raw, act_name, use_bias)
    st = Lux.initialstates(Random.default_rng(), layer)

    inputs, outputs = load_io_pair(case.io_path)
    # PyTorch (in_dims, L, B) complex -> Julia (B, L, in_dims) -> permute.
    x = permutedims(inputs["x"], (3, 2, 1))
    y_expected = permutedims(outputs["y"], (3, 2, 1))

    y_got, _ = layer(x, ps, st)
    y_got = ComplexF32.(y_got)
    err = maximum(abs.(y_got .- y_expected))

    status = err <= tol ? "PASS" : "FAIL"
    @info "case=$(case.name) act=$act_name bias=$use_bias max|err|=$(round(err, sigdigits=5)) ($status)"
    return err
end

function main()
    cases = enumerate_cases(FIXTURES)
    isempty(cases) &&
        error("no ResonantSTFT fixtures in $FIXTURES -- run generate_parity_resonant_stft.py first")
    failures = String[]
    for case in cases
        tol = _tol_for(case.name)
        err = verify_case(case; tol = tol)
        if err > tol
            push!(failures, "$(case.name): max|err|=$err > tol=$tol")
        end
    end
    if !isempty(failures)
        for f in failures
            @error f
        end
        error("ResonantSTFT parity FAILED for $(length(failures)) case(s).")
    end
    @info "ResonantSTFT parity: ALL CASES PASS (tol=$TOL, long=$TOL_LONG)"
end

isinteractive() || main()
